[MESA]
VERSION = 2.1.8
BOARD = 7i95
BOARD_NAME = 7i95T
FIRMWARE = ./mesa-firmware/7i95t_1v3pkt.bin

[EMC]
VERSION = 1.1
MACHINE = Axiom AR8 Elite
DEBUG = 0x00000000

[HM2]
DRIVER = hm2_eth
ADDRESS = 192.168.1.121

[DISPLAY]
DISPLAY = axis
EDITOR = geany
PROGRAM_PREFIX = /media/nas/files/Haskins Guitars/gcode
POSITION_OFFSET = RELATIVE
POSITION_FEEDBACK = COMMANDED
MAX_FEED_OVERRIDE = 1.2
MIN_LINEAR_VELOCITY = 0.0
DEFAULT_LINEAR_VELOCITY = 25
MAX_LINEAR_VELOCITY = 50.0
CYCLE_TIME = 0.1
INTRO_GRAPHIC = emc2.gif
INTRO_TIME = 0
OPEN_FILE = ""
INCREMENTS = continuous, 10 mm, 1.0 mm, 0.10 mm, 0.01 mm
SPINDLE_INCREMENT = 1000
DEFAULT_SPINDLE_0_SPEED = 15000
MIN_SPINDLE_0_SPEED = 2000
MAX_SPINDLE_0_SPEED = 24000

EMBED_TAB_NAME    = Z Probe
EMBED_TAB_COMMAND = pyvcp z-probe-puck/pyvcp/ztouch.xml

[ZPUCK]
PUCK_THICKNESS = 25

SEARCH_FEED = 25
SEARCH_DISTANCE = -10

LATCH_BACKOFF = 0.5
LATCH_FEED = 5
LATCH_DISTANCE = -1

# Distance to raise after latch probe
FINAL_BACKOFF = 50

[RAPIDCHANGEATC]
NUM_POCKETS = 8

# Position of pocket #1
POCKET_BASE_X = 583
POCKET_BASE_Y = 99.5

# Distance between pockets (can be negative values)
POCKET_OFFSET_X = 0
POCKET_OFFSET_Y = 45

# Save Z height
#  Before any XY moves, will G53 G0 Z[#<_ini[RAPIDCHANGEATC]SAFE_Z>] to avoid collisions
#  Usually upper Z limit
SAFE_Z = 195

# RPM when loading
ENGAGE_LOAD_RPM = 1500
# Number of strikes during loading, usually 2, but 3 ok.
ENGAGE_LOAD_STRIKES = 1
# RPM when unloading, usually 300RPM higher than load
ENGAGE_UNLOAD_RPM = 1800
# Number of strikes during unloading, usually 1
ENGAGE_UNLOAD_STRIKES = 2

# Machine Z where nut breaks IR, or nut flush with top of changer
ENGAGE_Z_START = 85
# Machine Z at bottom of engage cycle
#  30mm from top of changer
#  ~34mm from IR break
ENGAGE_Z_END = 55
# Feed rate when engaging changer
ENGAGE_FEED = 2000

# motion.digital-in-xx connected to IR sensor
#   -1 disables IR
IR_DI = -1
# motion.digital-out-xx connected to cover output
#   -1 disables cover
COVER_DO = 0

# Toolsetter position
TOOLSET_X = 582.5
TOOLSET_Y = 55

# Feed rate when searching for end of tool
TOOLSET_SEARCH_FEED = 200
# Max distance to search (negative value on most machines)
TOOLSET_SEARCH_DISTANCE = -100
# Backoff distance from search contact to begin latch probe (positive value on most machines)
TOOLSET_LATCH_BACKOFF = 1
# Feed rate when doing more precise latch probe
TOOLSET_LATCH_FEED = 10
# Max distance to do latch probe, should be a little more than (negative value on most machines)
TOOLSET_LATCH_DISTANCE = -1.5
# Machine Z when nut would contact tool setter, used to calculate tool offset
TOOLSET_HEIGHT = 83

# Position to rapid to for manual tool changes
MANUAL_CHANGE_X = 582.5
MANUAL_CHANGE_Y = 0

# motion.digital-out-xx to trigger manual tool change UI
#   -1 disables manual tool changes
TOOL_CHANGE_DO = 1
# motion.digital-in-xx indicating manual tool change complete
#   -1 disables manual tool changes
TOOL_CHANGED_DI = 1

[PROBE]
USE_PROBE = versaprobe

[HALUI]
MDI_COMMAND = O<probe_z_puck> CALL

[KINS]
KINEMATICS = trivkins coordinates=XYZ
JOINTS = 3

[EMCIO]
EMCIO = iov2
CYCLE_TIME = 0.100
TOOL_TABLE = tool.tbl

[PYTHON]
TOPLEVEL = rapidchange/toplevel.py
PATH_PREPEND = ./rapidchange
PATH_APPEND = ~/linuxcnc/nc_files/examples/remap_lib/python-stdglue

[RS274NGC]
PARAMETER_FILE = parameters.var
#REMAP=M6    modalgroup=6 prolog=rapidchange_change_prolog ngc=rapidchange_m6 epilog=change_epilog
SUBROUTINE_PATH = \
rapidchange/subroutines\
:z-probe-puck/subroutines\
:~/linuxcnc/nc_files/remap-subroutines\
ON_ABORT_COMMAND=o<on_abort> call

[EMCMOT]
EMCMOT = motmod
COMM_TIMEOUT = 1.0
SERVO_PERIOD = 1000000

[TASK]
TASK = milltask
CYCLE_TIME = 0.010

[TRAJ]
COORDINATES = XYZ
LINEAR_UNITS = mm
ANGULAR_UNITS = degree
MAX_LINEAR_VELOCITY = 150.0
NO_FORCE_HOMING = 1

[HAL]
HALUI = halui
TWOPASS = on
HALFILE = hal/main.hal
HALFILE = hal/servos-xyz.hal
HALFILE = hal/spindle.hal
HALFILE = hal/probes.hal
HALFILE = hal/manual-toolchange.hal
#HALFILE = rapidchange/atc.hal
POSTGUI_HALFILE = hal/post-gui.hal

[AXIS_X]
MIN_LIMIT = 0
MAX_LIMIT = 607
MAX_VELOCITY = 150
MAX_ACCELERATION = 800

[JOINT_0]
CARD = 0
TAB = 0
AXIS = X
MIN_LIMIT = 0
MAX_LIMIT = 607
MAX_VELOCITY = 150
MAX_ACCELERATION = 800
TYPE = LINEAR
SCALE = 1000
DRIVE = Gecko 203v
STEP_INVERT = False
DIR_INVERT = True
STEPGEN_MAX_VEL = 180.00
STEPGEN_MAX_ACC = 960.00
DIRSETUP = 200
DIRHOLD = 200
STEPLEN = 1000
STEPSPACE = 2000
ENCODER_SCALE = 1000
FERROR = 0.005
MIN_FERROR = 0.0025
DEADBAND = 0
P = 1000
I = 0
D = 0
FF0 = 0
FF1 = 1
FF2 = 0.0001
BIAS = 0
MAX_OUTPUT = 0
MAX_ERROR = 0.0127
HOME_SEQUENCE = 1
HOME = 0
HOME_OFFSET = 0
HOME_SEARCH_VEL = -50
HOME_LATCH_VEL = -5

[AXIS_Y]
MIN_LIMIT = 0
MAX_LIMIT = 1210
MAX_VELOCITY = 150
MAX_ACCELERATION = 800

[JOINT_1]
CARD = 0
TAB = 1
AXIS = Y
MIN_LIMIT = 0
MAX_LIMIT = 1210
MAX_VELOCITY = 150
MAX_ACCELERATION = 800
TYPE = LINEAR
SCALE = 1000
DRIVE = Gecko 203v
STEP_INVERT = False
DIR_INVERT = False
STEPGEN_MAX_VEL = 180.00
STEPGEN_MAX_ACC = 960.00
DIRSETUP = 200
DIRHOLD = 200
STEPLEN = 1000
STEPSPACE = 2000
ENCODER_SCALE = 1000
FERROR = 0.005
MIN_FERROR = 0.0025
DEADBAND = 0
P = 1000
I = 0
D = 0
FF0 = 0
FF1 = 1
FF2 = 0.0001
BIAS = 0
MAX_OUTPUT = 0
MAX_ERROR = 0.0127
HOME_SEQUENCE = 1
HOME = 0
HOME_OFFSET = 0
HOME_SEARCH_VEL = -50
HOME_LATCH_VEL = -5

[AXIS_Z]
MIN_LIMIT = 0
MAX_LIMIT = 195
MAX_VELOCITY = 80
MAX_ACCELERATION = 800

[JOINT_2]
CARD = 0
TAB = 2
AXIS = Z
MIN_LIMIT = 0
MAX_LIMIT = 195
MAX_VELOCITY = 80
MAX_ACCELERATION = 800
TYPE = LINEAR
SCALE = -2000
DRIVE = Gecko 203v
STEP_INVERT = False
DIR_INVERT = False
STEPGEN_MAX_VEL = 96.00
STEPGEN_MAX_ACC = 960.00
DIRSETUP = 200
DIRHOLD = 200
STEPLEN = 1000
STEPSPACE = 2000
ENCODER_SCALE = 1000
FERROR = 0.005
MIN_FERROR = 0.0025
DEADBAND = 0
P = 1000
I = 0
D = 0
FF0 = 0
FF1 = 1
FF2 = 0.0001
BIAS = 0
MAX_OUTPUT = 0
MAX_ERROR = 0.0127
HOME_SEQUENCE = 0
HOME = 195
HOME_OFFSET = 195
HOME_SEARCH_VEL = 30
HOME_LATCH_VEL = 5
